# Generated by Django 4.2.3 on 2023-11-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasebilltransactionhistory",
            name="position",
            field=models.CharField(
                choices=[("company", "company"), ("staff", "staff")],
                default="company",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
