# Generated by Django 4.2.6 on 2023-12-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0002_paymentouthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentout',
            name='ref_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
