# Generated by Django 4.2.3 on 2023-11-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0002_purchasebilltransactionhistory_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasebilltransactionhistory", name="position",
        ),
    ]
