# Generated by Django 3.2.23 on 2023-12-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0004_salesinvoice_salesinvoiceitem_salesinvoicetransactionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchasedebit',
            fields=[
                ('pdebitid', models.AutoField(primary_key=True, serialize=False, verbose_name='pdid')),
                ('reference_number', models.TextField(blank=True, max_length=100, null=True)),
                ('debitdate', models.DateField(null=True)),
                ('billno', models.CharField(max_length=150, null=True)),
                ('billdate', models.CharField(max_length=100, null=True)),
                ('supply', models.CharField(max_length=150, null=True)),
                ('subtotal', models.CharField(max_length=100, null=True)),
                ('sgst', models.CharField(max_length=100, null=True)),
                ('cgst', models.CharField(max_length=100, null=True)),
                ('igst', models.CharField(max_length=100, null=True)),
                ('taxamount', models.CharField(max_length=100, null=True)),
                ('grandtotal', models.CharField(max_length=100, null=True)),
                ('adjustment', models.FloatField(blank=True, default=0, null=True)),
                ('paid_amount', models.FloatField(blank=True, null=True)),
                ('balance_amount', models.FloatField(blank=True, null=True)),
                ('payment_type', models.CharField(max_length=100, null=True)),
                ('cheque_no', models.CharField(default='', max_length=255, null=True)),
                ('upi_no', models.CharField(default='', max_length=255, null=True)),
                ('tot_debt_no', models.IntegerField(default=0, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.party')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.staff_details')),
            ],
        ),
        migrations.CreateModel(
            name='purchasedebit1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('pdebit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.purchasedebit')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.itemmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DebitnoteTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated')], max_length=20)),
                ('transactiondate', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('debitnote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.purchasedebit')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.staff_details')),
            ],
        ),
    ]
